sizdev/accounts/urls.py
from re import template
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import UserProfile
from .forms import UpdateProfileForm
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="profile"),
    path('profile/<pk>', UpdateProfileView.as_view(), name="update_pro"),
    path("profile/<str:user_detail>", user_detail, name="user_detail"),
    path("login/", LoginView.as_view(template_name='auth_login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("addpost/", AddPosts.as_view(), name="addpost"),
]

sizdev/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("posts/<str:post_slug>/", post_detail, name="post_detail"),
]

sizdev/sizdev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('messages/', include('message.urls', namespace='messages')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

sizdev/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IPAddressField
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Jobs(models.Model):
    name = models.CharField('Kasbingiz', max_length=150)
    job_slug = models.SlugField('slug')

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'

    def __str__(self):
        return self.name
        

class Skills(models.Model):
    name = models.CharField('skills', max_length=100)
    skill_slug = models.SlugField('slug')

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name
        

class Degree(models.Model):
    degree = models.PositiveIntegerField('degree')
    skills = models.ForeignKey(Skills, verbose_name=("degree_skills"), on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Degree'
        verbose_name_plural = 'Degree'

    def __str__(self):
        return str(self.degree)
        

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile', null=True)
    avatar = models.ImageField('avatar image', upload_to='user_avatars/', null=True, blank=True)
    job = models.ForeignKey(Jobs, related_name=("jobs"), on_delete=models.PROTECT, null=True, blank=True)
    birth = models.DateField("Tug'ilgan Kuningiz", auto_now=False, auto_now_add=False, null=True, blank=True)
    place = models.CharField('place', max_length=250, null=True, blank=True)
    phone = models.CharField('Telefon raqam', max_length=25, null=True, blank=True)
    python = models.CharField('Python', max_length=2, blank=True)
    php = models.CharField('PHP', max_length=2, blank=True)
    js = models.CharField('JS', max_length=2, blank=True)
    java = models.CharField('Java', max_length=2, blank=True)
    c = models.CharField('C,C++,C#', max_length=2, blank=True)
    edu = RichTextField("Ta'lim", null=True, blank=True)
    work = RichTextField('Ish', null=True, blank=True)
    bio = RichTextField('Bio', null=True, blank=True)


    class Meta:
        verbose_name = 'User_profile'
        verbose_name_plural = 'User_profiles'

    def get_absolute_url(self):
        return reverse("accounts:user_detail", kwargs={"user_detail": self.user.username})
    

sizdev/templates/add_post.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}

<br><br><br>
<form action="" method="POST">
    {% csrf_token %}
    <h4 class="">Maqola qo'shish</h4>
   
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group mb-4">
                <label for="formGroupExampleInput">Maqola nomi</label>
                <input name="title" type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group mb-4">
                <label for="formGroupExampleInput">Maqola tanasi</label>
                <textarea name="body" type="text" class="form-control" id="editor" placeholder=""></textarea>
            </div>
            <button class="btn btn-primary" type="submit">O'zgartirish</button>
            <a class="btn btn-secondary" href="./">Ortga</a>
        </div>
    </div>
</form>
{% endblock %}

sizdev/templates/auth_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>CORK Admin Template - Login Cover Page</title>
    <link rel="icon" type="image/x-icon" href="/static/assets/img/favicon.ico"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/static/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    <link href="/static/assets/css/authentication/form-1.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/forms/theme-checkbox-radio.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/forms/switches.css">
</head>
<body class="form">
    

    <div class="form-container">
        <div class="form-form">
            <div class="form-form-wrap">
                <div class="form-container">
                    <div class="form-content">

                        <h1 class=""><a href="index.html"><span class="brand-name">Siz-Dev</span></a>ga Kiring!</h1>
                        <p class="signup-link">Hisobingiz yo'qmi? <a href="{% url 'accounts:register' %}">Ro'yxatdan o'ting</a></p>
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{form}}    
                            <button class="btn btn-secondary" type="submit">Kirish</button>                   
                        </form>
                        <p class="terms-conditions">© 2020 All Rights Reserved. <a href="index.html">CORK</a> is a product of Designreset. <a href="javascript:void(0);">Cookie Preferences</a>, <a href="javascript:void(0);">Privacy</a>, and <a href="javascript:void(0);">Terms</a>.</p>

                    </div>                    
                </div>
            </div>
        </div>
        <div class="form-image">
            <div class="l-image">
            </div>
        </div>
    </div>

    <script>
        if ( window.history.replaceState ) {
         window.history.replaceState( null, null, window.location.href );
        }
        var user = document.querySelector('#id_username');
        user.className = 'form-control mb-3';
        var pass = document.querySelector('#id_password');
        pass.className = 'form-control mb-3';
    </script>
    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="/static/assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="/static/bootstrap/js/popper.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="/static/assets/js/authentication/form-1.js"></script>

</body>
</html>

sizdev/templates/auth_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>CORK Admin Template - Register Login Cover Page</title>
    <link rel="icon" type="image/x-icon" href="/static/assets/img/favicon.ico"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/static/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    <link href="/static/assets/css/authentication/form-1.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->    
    <link rel="stylesheet" type="text/css" href="/static/assets/css/forms/theme-checkbox-radio.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/forms/switches.css">
</head>
<body class="form">

    <div class="form-container">
        <div class="form-form">
            <div class="form-form-wrap">
                <div class="form-container">
                    <div class="form-content">

                        <h1 class=""><a href="index.html"><span class="brand-name">Siz-Dev</span></a>ga kirish uchun<br>Ro'yxatdan o'ting</h1>
                        <p class="signup-link">Hisobingiz bormi? <a href="{% url 'accounts:login' %}">Kirish</a>ni bosing.</p>
                        <form class="text-left" method="POST">
                            {% csrf_token %}
                            {{form}}
                            <button class="btn btn-success text-dark mt-3" type="submit">Ro'yxatdan o'tish</button>
                        </form>                        
                        <p class="terms-conditions">© 2020 All Rights Reserved. <a href="{% url 'main:home' %}">Siz-Dev</a> is a product of Designreset. <a href="javascript:void(0);">Cookie Preferences</a>, <a href="javascript:void(0);">Privacy</a>, and <a href="javascript:void(0);">Terms</a>.</p>

                    </div>                    
                </div>
            </div>
        </div>
        <div class="form-image">
            <div class="l-image">
            </div>
        </div>
    </div>

    <script>
        if ( window.history.replaceState ) {
         window.history.replaceState( null, null, window.location.href );
        }
        document.querySelector('#id_username').className = 'form-control mb-3';
        document.querySelector('#id_password1').className = 'form-control mb-3';
        document.querySelector('#id_password2').className = 'form-control mb-3';
        document.querySelector('#id_first_name').className = 'form-control mb-3';
        document.querySelector('#id_last_name').className = 'form-control mb-3';
        document.querySelector('#id_email').className = 'form-control mb-3';
    </script>
    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="/static/assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="/static/bootstrap/js/popper.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="/static/assets/js/authentication/form-1.js"></script>

</body>
</html>

sizdev/templates/index.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}



<div class="">
    <br><br><br><br>
    <div class="display-4">Imkoniyatlar</div>
    <hr>
    <div class="row">
        <div class="col-lg-4 col-sm-12">
            <div class="infobox-2 bg-dark text-dark card p-3 mt-2">
                <h5 class="">Bepul va foydali</h5>
                <hr>
                <p class="">Bizning ma'lumotlar mutlaqo bepul, hamda maqolalarni cheksiz yuklashingiz mumkun.</p>
                <a class="btn btn-secondary" href="">Ko'proq</a>
            </div>
        </div>
        <div class="col-lg-4 col-sm-12">
            <div class="infobox-2 bg-dark text-dark card p-3 mt-2">
                <h5 class="">Layout Package</h5>
                <hr>
                <p class="">Lorem ipsum dolor sit amet, labore et dolore magna aliqua.</p>
                <a class="btn btn-primary" href="">Ko'proq</a>
            </div>
        </div>
        <div class="col-lg-4 col-sm-12">
            <div class="infobox-2 bg-dark text-dark card p-3 mt-2">
                <h5 class="">Layout Package</h5>
                <hr>
                <p class="">Lorem ipsum dolor sit amet, labore et dolore magna aliqua.</p>
                <a class="btn btn-secondary" href="">Ko'proq</a>
            </div>
        </div>
    </div>
</div>


<div class=" mt-5">
    <div class="display-4">So'ngi maqolalar</div>
    <hr>
    <div class="row">
    {% for post in post %}
            
        <div class="col-lg-6 col-sm-12">
            
            <div class="card component-card_2 m-2">
                <div class="card-body">
                    <div class="">
                    <h3 class="card-title">{{post.title}}</h3>
                    <a href="{{u_detail.get_absolute_url}}" class="mt-4"><h4>@{{post.admin.username}}</h4></a>
                    </div><hr>
                    <p class="card-text">{{post.body|truncatewords:'50'|safe}}</p>
                    <hr>
                    <a href="{{post.get_absolute_url}}" class="btn btn-secondary">Ko'proq</a>
                </div>
            </div>
                
        </div>
                

    {% endfor %}
        
    </div>
</div>


<div class=" mt-5">
    <div class="display-4">So'ngi foydalanuvchilar</div>
    <hr>
    <div class="row">
    {% for post in last %}
            
        <div class="col-lg-6 col-sm-12">
            
            <div class="card component-card_2 m-2">
                <div class="card-body">
                    <div class="">
                    <h3 class="card-title">Ismi:{{post.first_name}}</h3>
                    <a href="{{u_detail.get_absolute_url}}" class="mt-4"><h4>@{{post.username}}</h4></a>
                    </div><hr>
                    <p class="card-text"><b> Bio: </b>{{post.user_profile.bio|truncatewords:'20'}}</p>
                    <hr>
                    <a href="{{post.user_profile.get_absolute_url}}" class="btn btn-danger">Ko'proq</a>
                </div>
            </div>
                
        </div>
                

    {% endfor %}
        
    </div>
</div>
{% endblock content %}

sizdev/templates/post_detail.html
{% extends 'wrapper.html' %}
{% block content %}
<br><br><br>
<div class="container">
    <nav class="breadcrumb-two" aria-label="breadcrumb">
        <ol class="breadcrumb bg-secondary">
            <li class="breadcrumb-item"><a href="{% url 'main:home' %}">Bosh sahifa</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Maqolalar</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="javascript:void(0);">{{post.post_slug}}</a></li>
        </ol>
    </nav>
    <h1>{{post.title}}</h1>
    <div class="d-flex"><h3>{{post.admin.first_name}}</h3><a class="link p-2" href="">@{{post.admin.username}}</a></div>
    <hr>
    <p>{{post.body|safe}}</p>
</div>
{% endblock content %}

sizdev/templates/profile.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
 <!--  BEGIN CONTENT AREA  -->
 <div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-spacing">

            <!-- Content -->
            <div class="col-xl-4 col-lg-6 col-md-5 col-sm-12 layout-top-spacing">

                <div class="user-profile layout-spacing">
                    <div class="widget-content widget-content-area">
                        <div class="justify-content-between">
                            <h3 class="">Ma'lumoti</h3>
                            <a href="{% url 'accounts:addpost' %}" class="mt-2 edit-profile"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-folder-plus"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path><line x1="12" y1="11" x2="12" y2="17"></line><line x1="9" y1="14" x2="15" y2="14"></line></svg><span class="icon-name"> Maqola qo'shish</span></a>
                            <a href="{% url 'accounts:update_pro' request.user.user_profile.id %}" class="mt-2 edit-profile"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg><span class="icon-name"> Profilni tahrirlash</span></a>
                        </div><br>
                        <div class="user-info">
                            <h3 class="">{{request.user.first_name}} <br>{{request.user.last_name}}</h3>
                        </div>
                        <div class="user-info-list">

                            <div class="">
                                <ul class="contacts-block list-unstyled">
                                    <li class="contacts-block__item mt-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-coffee"><path d="M18 8h1a4 4 0 0 1 0 8h-1"></path><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"></path><line x1="6" y1="1" x2="6" y2="4"></line><line x1="10" y1="1" x2="10" y2="4"></line><line x1="14" y1="1" x2="14" y2="4"></line></svg> {{pro.user_profile.job}}
                                    </li>
                                    <li class="contacts-block__item mt-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg> {{pro.user_profile.birth}}
                                    </li>
                                    <li class="contacts-block__item mt-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg> {{pro.user_profile.place}}
                                    </li>
                                    <li class="contacts-block__item mt-2">
                                        <a href="{{request.user.username}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg> {{request.user.email}}</a>
                                    </li>
                                    <li class="contacts-block__item mt-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg> {{pro.user_profile.phone}}
                                    </li>
                                   
                                </ul>
                            </div>                                    
                        </div>
                    </div>
                </div>

                <div class="education layout-spacing ">
                    <div class="widget-content widget-content-area">
                        <h3 class="">Ta'limi haqida</h3>
                        {{request.user.user_profile.edu|safe}}
                    </div>
                </div>

                <div class="work-experience layout-spacing ">
                    
                    <div class="widget-content widget-content-area">

                        <h3 class="">Ishlashi haqida</h3>
                        
                        {{request.user.user_profile.work|safe}}
                    </div>

                </div>

            </div>

            <div class="col-xl-8 col-lg-6 col-md-7 col-sm-12 layout-top-spacing">

                <div class="skills layout-spacing ">
                    <div class="widget-content widget-content-area">
                        <h3 class="">Darjalar</h3>
                        <span>Python</span> | <span>{{pro.user_profile.python}}%</span> 
                        <div class="progress br-30">
                            <div class="progress-bar bg-info" role="progressbar" style="width: {{pro.user_profile.python}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div class="progress-title"></div></div>
                        </div>
                        <span>PHP</span> | <span>{{pro.user_profile.php}}%</span>
                        <div class="progress br-30">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: {{pro.user_profile.php}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div class="progress-title"> </div></div>
                        </div>
                        <span>JS</span> | <span>{{pro.user_profile.js}}%</span> 
                        <div class="progress br-30">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: {{pro.user_profile.js}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div class="progress-title"></div></div>
                        </div>
                        <span>Java</span> | <span>{{pro.user_profile.java}}%</span> 
                        <div class="progress br-30">
                            <div class="progress-bar bg-success" role="progressbar" style="width: {{pro.user_profile.java}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div class="progress-title"></div></div>
                        </div>
                        <span>C,C++,C#</span> | <span>{{pro.user_profile.c}}%</span> 
                        <div class="progress br-30">
                            <div class="progress-bar bg-primary" role="progressbar" style="width: {{pro.user_profile.c}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div class="progress-title"></div></div>
                        </div>
                    </div>
                </div>

                <div class="bio layout-spacing ">
                    <div class="widget-content widget-content-area">
                        <h3 class="">Bio</h3>
                        {{request.user.user_profile.bio|safe}}

                    </div>                                
                </div>

            </div>

        </div>
        </div>
{% endblock content %}

sizdev/templates/update_pro.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}

<br><br><br>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4 class="">Profilni tahrirlash</h4>
   
    <div class="row">
        <div class="col-lg-7 col-sm-12 ml-2 mr-2">
            
            {{form}}
            <button class="btn btn-primary" type="submit">O'zgartirish</button>
            <a class="btn btn-secondary" href="../">Ortga</a>
        </div>
    </div>
</form>


<script>
    document.querySelector('#id_job').className = 'form-control mb-3'
    document.querySelector('#id_birth').className = 'form-control mb-3'
    document.querySelector('#id_phone').className = 'form-control mb-3'
    document.querySelector('#id_python').className = 'form-control mb-3'
    document.querySelector('#id_php').className = 'form-control mb-3'
    document.querySelector('#id_js').className = 'form-control mb-3'
    document.querySelector('#id_java').className = 'form-control mb-3'
    document.querySelector('#id_c').className = 'form-control mb-3'
    document.querySelector('#id_place').className = 'form-control mb-3'
    document.querySelector('#id_bio').className = 'form-control mt-2 bio'
    document.querySelector('#id_edu').className = 'form-control mt-2 bio'
    document.querySelector('#id_work').className = 'form-control mt-2 bio'
</script>

{% endblock %}